repository:
  name: test-repository
  description: Just a small test repository for testing different configuration files
  homepage: ''
  topics: tests,configuration,other
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

branches:
  - name: master
  - name: develop

labels:
  - name: bug
    color: d73a4a
