repository:
  name: test-repository
  description: Just a small test repository for testing different configuration files
  homepage: ''
  topics: tests,configuration,other
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
